### ISSUE TITLE
Formats for Unwrapped instances?

### ISSUE THREAD

**Issue by lunaryorn** [julienrf/play-json-derived-codecs#37]
Does this library provide formats for datatypes with Unwrapped instances, e.g. `AnyVal` derived wrapper classes, such as `case class Foo(value: String) extends AnyVal`, which should be serialized as simple JSON string rather than as object with a `value` key?

**Comment by julienrf** [comment]
Hi, no the derivation process does not perform that automatically.

**Comment by lunaryorn** [comment]
@julienrf That's unfortunate. I'm looking into replacing our own custom derivations for Play JSON type classes with this library, but we need unwrapped serialisation.

Would it be possible to add support for Unwrapped to this library?  I'm not familiar with this code—our own derivations are quite different—but could you point me into the right directions so that I could prepare a PR—provided that you'd like to add this feature, of course.

**Comment by julienrf** [comment]
I like the idea, though I think that ideally the behavior should be configurable. I’m thinking of improving the derivation process to make it more extensible… Maybe we’ll think about the configurability once done.

So, if you want to do a PR, here are the steps to follow:
- Add a phantom type to the `DerivedReads` and `DerivedOWrites` typeclasses, to keep track of the original derived type (rather than only its “generic” shape) ;
- Add the following derivation rule:

~~~ scala
implicit def deriveAnyVal[A <: AnyVal, B](implicit
  bReads: Reads[B]
): DerivedReads[A, FieldType[_, B] :: HNil]
~~~

**Comment by lunaryorn** [comment]
I'll take look.  May take a while though, there's a lot of work currently :blush:
